# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a9eaf69d1db792ffd93230a4b93ab7918f6742eb49ecc4100f0a752d92f5bda12bc6b6209b06af924fbbbb6737b7f7c221b5537be4ecd441c32195490e5de2c

test:
  secret_key_base: 9d06c04158f20022f1a8ff91cb404c81e399b7d2b798b9ccede2619ed7f184e29c65a36403b6588f40782b4f250ba90f3e738e627c9e768a2d6e2e18a5e7c263

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
